### ISSUE TITLE
The error messages for un-fulfilled `write` and `write_read` calls is incorrect

### ISSUE THREAD

**Issue by jasonpeacock** [dbrgn/embedded-hal-mock#11]
They say `read call` instead of their respective actual calls:

https://github.com/dbrgn/embedded-hal-mock/blob/master/src/i2c.rs#L117

https://github.com/dbrgn/embedded-hal-mock/blob/master/src/i2c.rs#L136

Looks like a copy-pasta error :)

**Comment by jasonpeacock** [comment]
I'm working a PR for this now....

**Comment by dbrgn** [comment]
Good catch! A PR is welcome :slightly_smiling_face:

**Comment by jasonpeacock** [comment]
Yes, it definitely confused me!
