### ISSUE TITLE
Need ability to set that not calling "done()" on a mock is expected

### ISSUE THREAD

**Issue by ShakenCodes** [dbrgn/embedded-hal-mock#116]
There are cases in testing where calling "done()" on the Mock is not practical within the given test case, and it would be useful to be able to tell the Mock to not expect done() to be called and to not emit a warning in that case.

This came up in porting the @eldruin's [mlx9061x-rs](https://github.com/eldruin/mlx9061x-rs) to embedded-hal 1.0
Failing test cases are here: https://github.com/Radiator-Labs/mlx9061x-rs/actions/runs/9104910268/job/25029588644

The tests that fail are calling a fallible object create, which does not release the Mock and does not return the object when the creation fails. This means there is nothing to call done() on. Other test cases are able to call .destroy().done() on the returned object, which calls done() on the mock in the test context.

**Comment by dbrgn** [comment]
You should be able to pass a clone of the mock to the driver, and then call `.done()` on your copy, right?

(The mock has an `Arc` internally, so only a reference is being cloned.)

**Comment by ShakenCodes** [comment]
That sounds great. I'll give it a try right now.

**Comment by ShakenCodes** [comment]
Using clone() solves my issue. I am closing this request.

Thank you for the assist!
