### ISSUE TITLE
Contributors / Bus Factor

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/embedded-hal-mock#20]
@ryankurte since you've already added a few pull requests (thanks!), are you interested in co-maintaining this library, in order to increase the bus factor? If yes, I'll add you as a collaborator.

**Comment by ryankurte** [comment]
hey, yeah sure ^_^

i'd also support a move to the @rust-embedded org / hal team at some point if you're interested in that, but, i think we're probably good where we are while we're still experimenting.

**Comment by dbrgn** [comment]
Yep, I'm open to moving this project to @rust-embedded once it's a bit more complete and less experimental :slightly_smiling_face: 

I'll send you an invite!
