### ISSUE TITLE
StatefulOutputPin and ToggleableOutputPin

### ISSUE THREAD

**Issue by rubberduck203** [dbrgn/embedded-hal-mock#30]
Would you be interested in a PR that implements [ToggleableOutputPin](https://docs.rs/embedded-hal/0.2.3/embedded_hal/digital/v2/trait.ToggleableOutputPin.html)?

If I understand things correctly, the `Transaction` already knows it's state

https://github.com/dbrgn/embedded-hal-mock/blob/master/src/pin.rs#L51

so it should be relatively easy to implement [StatefulOutputPin](https://docs.rs/embedded-hal/0.2.3/embedded_hal/digital/v2/trait.StatefulOutputPin.html), which in turn would in turn make [implementing toggleable](https://docs.rs/embedded-hal/0.2.3/embedded_hal/digital/v2/toggleable/index.html) relatively trivial.

**Comment by rubberduck203** [comment]
This turned out to be more difficult than I had originally thought.
I ended up implementing a simple fake instead.

https://github.com/rubberduck203/switch-hal/blob/master/src/mock.rs

I'm still interesting in solving this, but am currently unsure of how to merge the two different implementations into a coherent design.

**Comment by ostenning** [comment]
+1, Support for `StatefulOutputPin` would be awesome
